ViraPag/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainapp/', include('mainapp.urls')),
    path('', include('interface.urls')),
]

mainapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.HomeView.as_view(),name='home' ),
    path('cadastro/',views.CadastroView.as_view(),name='cadastro'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('biblioteca/', views.Biblioteca.as_view(), name='biblioteca'),
    path('biblioteca/livro/<int:pk>/', views.LivroEmDetalhe.as_view(), name='livro_detail'),
    path('criarlivro/', views.LivroCreateView.as_view(), name='livro_create'),
    path('pesquisarlivro/', views.LivroSearchView.as_view(), name='livro_search'),
    path('atualizar/<int:pk>/', views.LivroUpdateView.as_view(), name='livro_update'),
    path('livro/deletar/<int:pk>/', views.LivroDeleteView.as_view(), name='livro_delete'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('perfil/', views.PerfilView.as_view(), name='perfil'),
    path('perfil/mudar_senha/', views.MudarSenhaView.as_view(),name='mudar_senha'),
    path('lista_desejos/add/', views.AddListaDesejosView.as_view(), name='add_lista_desejos'),
    path('lista_desejos/', views.ListaDesejosView.as_view(), name='lista_desejos'),
    path('lista_desejos/deletar/<int:livro_id>/', views.RemoverDaListaView.as_view(), name='remove_lista_desejos'),
    path('lista_desejos/add_para_colecao/<int:livro_id>/', views.AddParaColecaoView.as_view(), name='add_book_colecao'),
    path('book_history/', views.BookHistoryView.as_view(), name='book_history'),
    path('remove_history/<int:livro_id>/', views.RemoveFromHistoryView.as_view(), name='remove_history'),
    path('adicionar_comentario/<int:livro_id>/', views.AdicionarComentarioView.as_view(), name='adicionar_comentario'),
    path('deletar_comentario/<int:comentario_id>/', views.DeletarComentarioView.as_view(), name='deletar_comentario'),
    path('avaliacao/<int:livro_id>/', views.AvaliacaoLivroView.as_view(), name='avaliacao'),
    path('favorito/adicionar/<int:livro_id>/', views.AdicionarFavoritoView.as_view(), name='adicionar_favorito'),
]

mainapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings

class Categoria(models.Model):
    genero = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.genero

class Livro(models.Model):
    STATUS_LEITURA_CHOICES = [
        ('NL', 'Não Lido'),
        ('EL', 'Em Leitura'),
        ('L', 'Lido'),
    ]
    AVALIACAO_CHOICES = [
        (0, '0 Estrelas'),
        (1, '1 Estrela'),
        (2, '2 Estrelas'),
        (3, '3 Estrelas'),
        (4, '4 Estrelas'),
        (5, '5 Estrelas'),
    ]
    titulo = models.CharField(max_length=100)
    autor = models.CharField(max_length=100)
    anopublicado = models.IntegerField()
    genero=models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)
    status_leitura=models.CharField(max_length=2, choices=STATUS_LEITURA_CHOICES, default='NL')
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='livros')
    isbn = models.CharField(max_length=13, null=True)
    in_wishlist = models.BooleanField(default=False)
    in_collection = models.BooleanField(default=True)
    avaliacao = models.IntegerField(choices=AVALIACAO_CHOICES, null=True, blank=True)
    is_favorite = models.BooleanField(default=False)
    
    def _str_(self):
        return self.titulo
    
    def comentarios(self):
        return Comentario.objects.filter(livro=self)
    
class ListaDesejos(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='lista_desejos',null=True)
    livros = models.ManyToManyField('Livro', related_name='desejado_por')

    def _str_(self):
        return f" Lista de desejos de {self.usuario}"


class BookHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book_title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    date_started = models.DateField(default=timezone.now)
    date_finished = models.DateField(blank=True, null=True)

    def _str_(self):
        return f"{self.book_title} ({self.author})"

class Comentario(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField()
    data_publicacao = models.DateTimeField(default=timezone.now)
    livro = models.ForeignKey(Livro, on_delete=models.CASCADE, related_name='comentarios') 

    def _str_(self):
        return f"Comentário de {self.autor} em {self.livro}: {self.texto}"

virapag_all/mainapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings

class Categoria(models.Model):
    genero = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.genero

class Livro(models.Model):
    STATUS_LEITURA_CHOICES = [
        ('NL', 'Não Lido'),
        ('EL', 'Em Leitura'),
        ('L', 'Lido'),
    ]
    AVALIACAO_CHOICES = [
        (0, '0 Estrelas'),
        (1, '1 Estrela'),
        (2, '2 Estrelas'),
        (3, '3 Estrelas'),
        (4, '4 Estrelas'),
        (5, '5 Estrelas'),
    ]
    titulo = models.CharField(max_length=200)
    autor = models.CharField(max_length=100)
    anopublicado = models.IntegerField()
    genero=models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)
    status_leitura=models.CharField(max_length=2, choices=STATUS_LEITURA_CHOICES, default='NL')
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='livros')
    isbn = models.CharField(max_length=13, null=True)
    in_wishlist = models.BooleanField(default=False)
    in_collection = models.BooleanField(default=True)
    avaliacao = models.IntegerField(choices=AVALIACAO_CHOICES, null=True, blank=True)
    is_favorite = models.BooleanField(default=False)
    
    def _str_(self):
        return self.titulo
    
    def comentarios(self):
        return Comentario.objects.filter(livro=self)
    
class ListaDesejos(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='lista_desejos',null=True)
    livros = models.ManyToManyField('Livro', related_name='desejado_por')

    def _str_(self):
        return f" Lista de desejos de {self.usuario}"


class BookHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book_title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    date_started = models.DateField(default=timezone.now)
    date_finished = models.DateField(blank=True, null=True)

    def _str_(self):
        return f"{self.book_title} ({self.author})"

class Comentario(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField()
    data_publicacao = models.DateTimeField(default=timezone.now)
    livro = models.ForeignKey(Livro, on_delete=models.CASCADE, related_name='comentarios') 

    def _str_(self):
        return f"Comentário de {self.autor} em {self.livro}: {self.texto}"

mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth import logout, update_session_auth_hash
from django.db.models import Count, F
from django.views.decorators.csrf import csrf_protect
from django.utils.decorators import method_decorator
from django.contrib import messages
from .models import Livro, Categoria, ListaDesejos, BookHistory, Comentario
from django.contrib.auth.hashers import make_password
from .utils import fetch_book_info_by_title
from django.utils import timezone
from django.http import HttpResponseRedirect

class HomeView(View):
    def get(self, request):
        if not Categoria.objects.exists():
            categorias = [
                'Ficção Científica', 'Comédia', 'Esportes', 'História Infantil',
                'Suspense', 'Educacional', 'Romance', 'Aventura', 'Terror', 'Drama'
            ]
            for categoria in categorias:
                Categoria.objects.create(genero=categoria)
        
        contexto = {'user': request.user if request.user.is_authenticated else None}
        if request.user.is_authenticated:
            livros_usuario = Livro.objects.filter(usuario=request.user)
            total_livros = livros_usuario.count()
            generos_ordenados = livros_usuario.values('genero__genero').annotate(total=Count('genero')).order_by('-total')

            if generos_ordenados:
                generos_mais_comuns = generos_ordenados.filter(total=generos_ordenados.first()['total'])
                generos_menos_comuns = generos_ordenados.filter(total=generos_ordenados.last()['total'])

                contexto['genero_mais_comum'] = ', '.join([g['genero__genero'] for g in generos_mais_comuns if g['genero__genero']])
                contexto['genero_menos_comum'] = ', '.join([g['genero__genero'] for g in generos_menos_comuns if g['genero__genero']])

            else:
                contexto['genero_mais_comum'] = 'Indisponível'
                contexto['genero_menos_comum'] = 'Indisponível'

            contexto['total_livros'] = total_livros

        return render(request, 'mainapp/home.html', contexto)
       
class CadastroView(View):
    def get(self, request):
        return render(request, 'mainapp/cadastro.html')
    def post(self, request):
        username = request.POST.get('username')
        email = request.POST.get('email')  
        password = request.POST.get('password')

        if not username or not password:
            return render(request, 'mainapp/cadastro.html', {
                'error': 'Usuário e senha são campos obrigatórios.'
            })

        if User.objects.filter(username=username).exists():
            return render(request, 'mainapp/cadastro.html', {
                'error': 'Nome de usuário já existe.'
            })

        user = User(username=username, email=email)
        user.set_password(password)
        user.save()
        return redirect('login')  

class LoginView(LoginView):
    template_name = 'mainapp/login.html'  
    redirect_authenticated_user = True  
    next_page = reverse_lazy('home')
   
    
class LogoutView(View):

    @method_decorator(csrf_protect)
    def post(self, request):
        logout(request)
        return redirect('home')

class Biblioteca(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('home')
        else:
            livros = Livro.objects.filter(usuario=request.user, in_collection=True).order_by(F('is_favorite').desc(nulls_last=True))
            for livro in livros:
                book_info = fetch_book_info_by_title(livro.titulo)
                if book_info:
                    livro.cover_url = book_info.get('cover_url')
            
            return render(request, 'mainapp/biblioteca.html', {'livros': livros})
        
class LivroEmDetalhe(LoginRequiredMixin, View):
    def get(self, request, pk):
        livro = get_object_or_404(Livro, pk=pk)
        book_info = None
       
        if not livro.isbn:
            book_info = fetch_book_info_by_title(livro.titulo)
            if book_info:
                livro.isbn = book_info.get('isbn')
                livro.cover_url = book_info.get('cover_url')
                livro.save()
            else:
                livro.cover_url = book_info.get('cover_url') if livro.isbn else None
        
        
        comentarios = Comentario.objects.filter(livro=livro)
        
        return render(request, 'mainapp/livro_detail.html', {'livro': livro, 'comentarios': comentarios})



class LivroCreateView(LoginRequiredMixin, View):
    def get(self, request):
        categorias = Categoria.objects.all()
        return render(request, 'mainapp/livro_form.html', {'categorias': categorias})

    def post(self, request):
        titulo = request.POST.get('titulo').strip()
        autor = request.POST.get('autor').strip()
        anopublicado = request.POST.get('anopublicado').strip()
        genero_id = request.POST.get('genero').strip()
        
        if not titulo or not autor or not anopublicado:
            messages.error(request, 'Todos os campos são obrigatórios.')
            return redirect('livro_create')

        if Livro.objects.filter(titulo__iexact=titulo, usuario=request.user).exists():
            messages.error(request, 'Um livro com este nome já existe na sua biblioteca.')
            return redirect('livro_create')

        genero = get_object_or_404(Categoria, id=genero_id)
        Livro.objects.create(titulo=titulo, autor=autor, anopublicado=anopublicado, genero=genero, usuario=request.user)
        messages.success(request, 'Livro adicionado com sucesso!')
        return redirect('biblioteca')

class LivroSearchView(View):
    def get(self, request):
        return render(request, 'mainapp/livro_search.html', {'titulo': '', 'autor': ''})

    def post(self, request):
        titulo = request.POST.get('titulo', '').strip()
        autor = request.POST.get('autor', '').strip()

        livros = Livro.objects.filter(usuario=request.user)

        if titulo:
            livros = livros.filter(titulo__icontains=titulo)

        if autor:
            livros = livros.filter(autor__icontains=autor)

        if not titulo and not autor:
            messages.error(request, 'Preencha pelo menos um campo para buscar.')

        return render(request, 'mainapp/livro_search.html', {'titulo': titulo, 'autor': autor, 'livros': livros})

class LivroUpdateView(LoginRequiredMixin, View):
    def get(self, request, pk):
        livro = get_object_or_404(Livro, pk=pk)
        status_leitura = livro.status_leitura
        return render(request, 'mainapp/livro_update.html', {'livro': livro, 'categorias': Categoria.objects.all(), 'status_leitura': status_leitura})

    def post(self, request, pk):
        livro = get_object_or_404(Livro, pk=pk)
        livro.titulo = request.POST.get('titulo')
        livro.autor = request.POST.get('autor')
        livro.anopublicado = request.POST.get('anopublicado')
        livro.genero = get_object_or_404(Categoria, pk=request.POST.get('genero'))
        novo_status_leitura = request.POST.get('status_leitura')

        if livro.status_leitura != 'NL' and novo_status_leitura == 'NL':
            if BookHistory.objects.filter(user=request.user, book_title=livro.titulo, author=livro.autor).exists():
                BookHistory.objects.filter(user=request.user, book_title=livro.titulo, author=livro.autor).delete()
                messages.success(request, 'Livro editado com sucesso!')

        elif novo_status_leitura in ['L', 'EL']:
            if not BookHistory.objects.filter(user=request.user, book_title=livro.titulo, author=livro.autor).exists():
                BookHistory.objects.create(
                    user=request.user,
                    book_title=livro.titulo,
                    author=livro.autor,
                )
                messages.success(request, 'Livro editado com sucesso!')

        livro.status_leitura = novo_status_leitura

        if livro.status_leitura != 'L':
            livro.avaliacao = None

        livro.save()
        return redirect('biblioteca')

class LivroDeleteView(LoginRequiredMixin,View):
    def get(self, request, pk):
        livro = get_object_or_404(Livro, pk=pk)
        return render(request, 'mainapp/livro_confirm_delete.html', {'livro': livro})

    def post(self, request, pk):
        livro = get_object_or_404(Livro, pk=pk)
        livro.delete()
        return redirect('biblioteca')

class PerfilView(LoginRequiredMixin,View):
    def get(self, request):
        if not request.user.is_authenticated:
            
            return redirect('home')
        else:
            usuario=request.user.username
            email=request.user.email
            context = {'usuario': usuario, 'email': email}
            return render(request, 'mainapp/perfil.html', context)

class MudarSenhaView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'mainapp/mudar_senha.html')

    def post(self, request):
        senha_antiga = request.POST.get('senha_antiga')
        nova_senha = request.POST.get('nova_senha')
        confirmar = request.POST.get('confirmar')

        if not request.user.check_password(senha_antiga):
            messages.error(request, 'Sua senha antiga foi digitada errado. Tente novamente.')
        elif nova_senha != confirmar:
            messages.error(request, 'Por favor, digite sua senha nova igual ao escrito no primeiro campo.')
        else:
            request.user.password = make_password(nova_senha)
            request.user.save()
            update_session_auth_hash(request, request.user)  
            messages.success(request, 'Sua senha foi atualizada com sucesso!')

mainapp/templates/mainapp/add_lista.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'mainapp/css/mainapp.css' %}">
    
{% endblock %}

{% block 'dashboard' %}
<div class="container mt-5">
    <div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;">
        <div id="toastContainer" style="position: absolute; top: 0;">
        </div>
    </div>
</div>
<div class="container mt-5">
    <h2 class="mb-4">Adicione Livros à Sua Lista de Desejos</h2>
    <form method="post" class="mt-3">
        {% csrf_token %}
        <div class="form-group">
            <label for="titulo">Título:</label>
            <input type="text" class="form-control" id="titulo" name="titulo" placeholder="Digite o título do livro" required>
        </div>
        <div class="form-group">
            <label for="autor">Autor:</label>
            <input type="text" class="form-control" id="autor" name="autor" placeholder="Nome do autor" required>
        </div>
        <div class="form-group">
            <label for="anopublicado">Ano Publicado:</label>
            <input type="number" class="form-control" id="anopublicado" name="anopublicado" placeholder="Ano de publicação" required>
        </div>
        <div class="form-group">
            <label for="genero">Categoria:</label>
            <select class="form-control" id="genero" name="genero">
                {% for categoria in categorias %}
                <option value="{{ categoria.id }}">{{ categoria.genero }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        {% if messages %}
            {% for message in messages %}
            const toastContainer = document.getElementById('toastContainer');
            let toastClass = "";
            switch("{{ message.tags }}") {
                case "success":
                    toastClass = "bg-success text-white";
                    break;
                case "error":
                    toastClass = "bg-danger text-white";
                    break;
                
                default:
                    toastClass = "bg-primary text-white";
            }
    
            const toastHtml = `
                <div class="toast ${toastClass}" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000">
                    <div class="toast-header">
                        <strong class="mr-auto">Notificação</strong>
                        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="toast-body">
                        {{ message }}
                    </div>
                </div>`;
            toastContainer.insertAdjacentHTML('beforeend', toastHtml);
            {% endfor %}
            $('.toast').toast('show');
        {% endif %}
    });
    </script>
{% endblock %}

mainapp/templates/mainapp/adicionar_comentario.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'mainapp/css/mainapp.css' %}">
{% endblock %}

{% block 'dashboard' %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2>Adicionar Comentário para o Livro "{{ livro.titulo }}"</h2>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="comentario_texto">Comentário:</label>
            <textarea class="form-control" id="comentario_texto" name="texto" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Salvar Comentário</button>
        <a href="{% url 'livro_detail' livro.id %}" class="btn btn-secondary" style="margin-left: 10px;">Voltar</a>
    </form>
</div>
{% endblock %}

mainapp/templates/mainapp/avaliacao.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'mainapp/css/mainapp.css' %}">
{% endblock %}

{% block 'dashboard' %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2>Avaliação para o Livro "{{ livro.titulo }}"</h2>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="avaliacao">Avaliação:</label>
            <select class="form-control" id="avaliacao" name="avaliacao">
                <option value="0" {% if livro.avaliacao == 0 %}selected{% endif %}>Sem avaliacão</option>
                <option value="1" {% if livro.avaliacao == 1 %}selected{% endif %}>1 Estrela</option>
                <option value="2" {% if livro.avaliacao == 2 %}selected{% endif %}>2 Estrelas</option>
                <option value="3" {% if livro.avaliacao == 3 %}selected{% endif %}>3 Estrelas</option>
                <option value="4" {% if livro.avaliacao == 4 %}selected{% endif %}>4 Estrelas</option>
                <option value="5" {% if livro.avaliacao == 5 %}selected{% endif %}>5 Estrelas</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Avaliar</button>
        <a href="{% url 'livro_detail' livro.id %}" class="btn btn-secondary" style="margin-left: 10px;">Voltar</a>
    </form>
</div>
{% endblock %}

mainapp/templates/mainapp/biblioteca.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'mainapp/css/mainapp.css' %}">
{% endblock %}

{% block 'dashboard' %}
<div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;">
    <div id="toastContainer" style="position: absolute; top: 0;">
    </div>
</div>
<div class="container mt-4">
    <h2>Livros</h2>
    <div class="list-group mt-3">
        {% for livro in livros %}
        <a href="{% url 'livro_detail' livro.id %}" class="list-group-item list-group-item-action d-flex align-items-start">
            <img src="{{ livro.cover_url }}" alt="Capa do livro {{ livro.titulo }}" class="book-cover img-fluid mr-3" style="width: 100px; height: auto;">
            <div>
                <div>{{ livro.titulo }} por {{ livro.autor }} ({{ livro.anopublicado }})</div>
                <div>Status de leitura: {{ livro.get_status_leitura_display }}</div>
            </div>
            {% if livro.is_favorite %}
            <span class="badge badge-primary badge-pill ml-auto" style="background-color: #F4C430;  color: black;" >Favorito</span>
            {% endif %}
        </a>
        {% empty %}
        <p>Nenhum livro adicionado ainda.</p>
        {% endfor %}
    </div>
    <a href="{% url 'livro_create' %}" class="btn btn-primary mt-3">Adicione um novo livro.</a>
    <a href="{% url 'livro_search' %}" class="btn btn-primary mt-3">Pesquise um livro adicionado.</a>
       
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        {% if messages %}
            {% for message in messages %}
            const toastContainer = document.getElementById('toastContainer');
            
            let toastClass = "";
            switch("{{ message.tags }}") {
                case "success":
                    toastClass = "bg-success text-white";
                    break;
                case "error":
                    toastClass = "bg-danger text-white";
                    break;
                
                default:
                    toastClass = "bg-primary text-white";
            }
    
            const toastHtml = `
                <div class="toast ${toastClass}" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000">
                    <div class="toast-header">
                        <strong class="mr-auto">Notificação</strong>
                        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="toast-body">
                        {{ message }}
                    </div>
                </div>`;
            toastContainer.insertAdjacentHTML('beforeend', toastHtml);
            {% endfor %}
            $('.toast').toast('show');
        {% endif %}
    });
    </script>
{% endblock %}

mainapp/templates/mainapp/book_history.html
{% extends "base.html" %}

{% block 'head' %}
{% load static %}
<link rel="stylesheet" href="{% static 'mainapp/css/mainapp.css' %}">
{% endblock %}

{% block 'dashboard' %}
<div class="container mt-4">
    <h2>Histórico de {{ user.username }}</h2>
    {% if messages %}
    <div class="alert alert-danger">
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}
    
    <div class="list-group mt-3">
        {% for book in book_history %}
        <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
            <div>
                <div>{{ book.book_title }} - {{ book.author }} ({{ book.date_started|date:"M/Y" }})</div>
            </div>
            <div>
                <form action="{% url 'remove_history' livro_id=book.id %}" method="post" style="display:inline-block;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Remover</button>
                </form>
            </div>
        </div>
        {% empty %}
        <p>Nenhum livro no histórico.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/livro_search.html
{% extends "base.html" %}

{% block 'head' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'mainapp/css/mainapp.css' %}">
{% endblock %}

{% block 'dashboard' %}
<div class="container mt-4">
    <h2>Pesquisa Avançada de Livros</h2>

    <form method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-3">
                <label for="id_titulo">Título:</label>
                <input type="text" id="id_titulo" name="titulo" class="form-control" value="{{ titulo }}">
            </div>
            <div class="form-group col-md-3">
                <label for="id_autor">Autor:</label>
                <input type="text" id="id_autor" name="autor" class="form-control" value="{{ autor }}">
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Pesquisar</button>
    </form>

    {% if livros %}
    <div class="list-group mt-3">
        {% for livro in livros %}
        <a href="{% url 'livro_detail' livro.id %}" class="list-group-item list-group-item-action d-flex align-items-start">
            {% if livro.cover_url %}
                <img src="{{ livro.cover_url }}" alt="Capa do livro {{ livro.titulo }}" class="book-cover img-fluid mr-3" style="width: 100px; height: auto;">
            {% else %}
                <div class="book-cover-placeholder mr-3"></div>
            {% endif %}
            <div>
                <div>{{ livro.titulo }} por {{ livro.autor }} ({{ livro.anopublicado }})</div>
                <div>Status de leitura: {{ livro.get_status_leitura_display }}</div>
            </div>
            {% if livro.is_favorite %}
            <span class="badge badge-primary badge-pill ml-auto" style="background-color: #F4C430; color: black;">Favorito</span>
            {% endif %}
        </a>
        {% empty %}
        <p>Nenhum livro encontrado.</p>
        {% endfor %}
    </div>
    {% else %}
    <p>Nenhum resultado encontrado para os critérios de pesquisa.</p>
    {% endif %}
</div>
{% endblock %}

mainapp/templates/mainapp/perfil.html
{% extends "base.html" %}


{% block 'head' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'mainapp/css/mainapp.css' %}">
{% endblock %}

{% block 'dashboard' %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="user-info">
                <p><strong>Nome de usuário:</strong> {{ usuario }}</p>
                <p><strong>Email:</strong> {{ email }}</p>
                <a href="{% url 'mudar_senha' %}" class="btn btn-warning">Mude sua senha</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}